modLoader="javafml"
loaderVersion="[1,)"
license="MIT License"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="MC_CaoFangKuai"
description='''非主动退出服务器后自动重连
使用/#来配置模组'''
logoFile="assets/autoreconnect/icon.png"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
versionRange="${neo_version}"
ordering="NONE"
side="BOTH"

[[mixins]]
config="autoreconnect.mixins.json"